### ISSUE TITLE
Google wont allow sign in to tiktok

### ISSUE THREAD

**Issue by Freffles** [adhikary97/TikTok-Bot#6]
Got this working to the point where I needed to login to tiktok. The usual login window appeared, selected login with google and then the google login/verification window popped up. Had a banner across the top indicating the browser was being controlled by test software. Allowed me to enter my email address then would not allow any further progress because of security issues.

If I try to login via email/password then tiktok informs that "too many attempts", even on first attempt.

**Comment by eulogioqt** [comment]
happened the same to me, did you find any solution?

**Comment by Freffles** [comment]
Nope. Gave up. Not sure there is anything worth beating my head against a wall for. I can schedule a post in TikTok already on PC (business account). The trade-off is that you can only have 150 characters on PC. Can't schedule on the mobile app but can have many more characters. Was hoping this would provide a way to have a bigger caption than via browser/app on PC but I doubt that it works that way. Tempted to have a crack at doing this myself from scratch but not enough hours in the day.
